twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]

    globals:
        pdf_path_css: "%kernel.project_dir%/public/"
        pdf_path_image_upload: "%kernel.project_dir%/public/upload/"
